### ISSUE TITLE
Optionally disable capitalization: interpret the text with all lowercase words as without names.

### ISSUE THREAD

**Issue by AlekseiMarinichenko** [derek73/python-nameparser#113]
**CURRENT BEHAVIOR** 

```
#  Example 1

>>> input_text = "foo bar spam eggs"
>>> name = HumanName(input_text)
>>> name.first
foo                          
>>> name.last
eggs                        



#  Example 2

input_text = "this text makes no sense, there are no names here"
name = HumanName(input_text)
>>> name.first
there                          
>>> name.last
this text makes no sense        
```

**EXPECTED BEHAVIOR** 

```
>>> input_text = "good films make your life better"
       # ALL WORDS ARE LOWERCASE = NO NAMES IN THE TEXT !!!
>>> name = HumanName(input_text)
>>> name.first
None
>>> name.last
None
```

**Comment by derek73** [comment]
The primary use case of this parser, at least initially, was to accept a name as input and provide a way easily split that name up into its useful pieces. The parser always assumes the string it receives is a name. Sometimes when humans provide their name, they do not capitalize it, but users of the parser would like those names to be nicely formatted with capitalization. This is the purpose of capitalization support. Capitalization does not run by default, the programmer must call `capitalize()`.

This parser is not intended to discover names in unstructured text. So I do not think that the expected behavior you described is something this parser should do. From the viewpoint of this parser, you can go ahead and name your kids "good films make your life better" if you choose. :)

**Comment by derek73** [comment]
Feel free to reopen this issue if I've misunderstood the request.

**Comment by AlekseiMarinichenko** [comment]
Thank you for the explanation. I was confused by a README and thought that the library aimed to recognize names in any text. Now I understand the purpose of the package.
