### ISSUE TITLE
San San Chiou

### ISSUE THREAD

**Issue by MrMorden81** [derek73/python-nameparser#33]
>>> from nameparser import HumanName
>>> name = HumanName('San San Chiou')
>>> name
<HumanName : [
	title: '' 
	first: 'San San Chiou' 
	middle: '' 
	last: '' 
	suffix: ''
	nickname: ''
]>

I expected "San" for first name, "San" for middle name, and "Chiou" for last name.

**Comment by derek73** [comment]
This is because "san" is currently in the prefixes constant. Prefixes join to the piece after it. This is because there are a few Spanish last names that use "san" as a prefix:

http://genealogy.familyeducation.com/browse/origin/spanish?page=7

* San Jose
* San Juan
* San Martin
* San Miguel
* San Nicolas
* San Pedro
* San Roman


You can fix this in your own project by removing 'san' from the prefixes constant:

```python
    >>> from nameparser.config import CONSTANTS
    >>> CONSTANTS.prefixes.remove('san')
```

I guess the parser could only join prefixes for last names, which seems reasonable.

**Comment by MrMorden81** [comment]
Got it, thank you!
