### ISSUE TITLE
Inputting Accents causes exception (UnicodeDecodeError)

### ISSUE THREAD

**Issue by noescapeartist** [derek73/python-nameparser#38]
name = HumanName("Beyoncé Knowles")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)

**Comment by derek73** [comment]
The parser uses UTF8. Not sure why it's trying to decode to ascii.  Are you perhaps on windows? What is your terminals encoding? Need more info to reproduce.  Works fine for me.

**Comment by noescapeartist** [comment]
I'm on a mac.  I'm using terminal with UTF-8 encoding.  But the same arises when I try to parse name data from a db in a web framework.

**Comment by derek73** [comment]
Weird. Ok, i just tried it an got the same thing. I must broke something. I'll look into it.

**Comment by derek73** [comment]
that should fix it for now. You can use this to give it a try before I push to pypi.

`pip install -e git+git://github.com/derek73/python-nameparser.git#egg=nameparser`

I guess because the tests use `unicode_literals`, all the strings start out as unicode so they aren't catching those encoding problems. I should probably update the tests too before I push a new release.
