### ISSUE TITLE
error on two joiner words

### ISSUE THREAD

**Issue by daryanypl** [derek73/python-nameparser#53]
If a name contains two joiner words one after another, s.a. "John of the Doe", get:
HumanName:ERROR:parser.py:Couldn't find 'The' in pieces.
error.

**Comment by derek73** [comment]
I cannot replicate this. Could you provide more information to help me replicate?

$ python tests.py "John of the Doe"
<HumanName : [
	title: '' 
	first: 'John of the Doe' 
	middle: '' 
	last: '' 
	suffix: ''
	nickname: ''
]>
$ python tests.py "John of The Doe"
<HumanName : [
	title: '' 
	first: 'John of The Doe' 
	middle: '' 
	last: '' 
	suffix: ''
	nickname: ''
]>

**Comment by daryanypl** [comment]
Sure.

from nameparser import HumanName

def test_name(name):
    HumanName('Bob, Author of The book of the allies')

I've played around a bit, and it's not all "of the" combinations.  For
example,

HumanName('Bob, Author of the book of the allies')
and
HumanName('Bob, Author of The book on allies')
are both fine.


Darya

**Comment by derek73** [comment]
'Bob, Author of the book of the allies' doesn't give the error, so I think it's related to capitalization of multiple conjunctions when combined with titles. Should be parsed as a title though. That `join_on_conjunctions()` part of the parse code makes my head melt but I'll poke around and see if I can figure it out.

```
$ python tests.py "Bob, Author of the book of the allies"
<HumanName : [
	title: '' 
	first: 'Author of the book of the allies' 
	middle: '' 
	last: 'Bob' 
	suffix: ''
	nickname: ''
]>
```

**Comment by daryanypl** [comment]
Happy to help test.

Darya

**Comment by derek73** [comment]
I ended up refactoring that `join_on_conjunctions()` method entirely because, even though I wrote it, I couldn't understand it. It was one of those "I guess it works so don't fix it" things. But now I think I've got it fixed, all the test are passing. 

It's in master now. I think you can install it with `pip install -e git+git://github.com/derek73/python-nameparser.git@v0.5.0-beta#egg=nameparser`. I also made [pre-release v0.5.0-beta](https://github.com/derek73/python-nameparser/releases/tag/v0.5.0-beta) if that's easier. Give a try and let me know if you run into any issues.

**Comment by derek73** [comment]
I'm going to go ahead and close this ticket and make a new release. Let me know if you have any problems with it.

**Comment by daryanypl** [comment]
Thanks, and sorry for the delay.  Verified that "of the of the" no longer
throws an error.  Found a few more interesting special cases.  Filed here:
https://github.com/derek73/python-nameparser/issues/57 .

Darya
