### ISSUE TITLE
{first} {last}, {suffix} is incorrectly recognized as {first}, {title}

### ISSUE THREAD

**Issue by Darayavaush** [derek73/python-nameparser#62]
```
>>> name = "John Smith, Dr."
>>> nameparser.HumanName(name)
<HumanName : [
        title: 'Dr.'
        first: 'John Smith'
        middle: ''
        last: ''
        suffix: ''
        nickname: ''
]>
```
But if I insert a comma, it is recognized as per documentation:
```
>>> name = "John, Smith, Dr."
>>> nameparser.HumanName(name)
<HumanName : [
        title: ''
        first: 'Smith'
        middle: ''
        last: 'John'
        suffix: 'Dr.'
        nickname: ''
]>
```

**Comment by derek73** [comment]
It turns out this is because "Dr" is not an expected suffix, yet. It works as expected with "MD". "Dr" is currently only expected as a prefix. 

It makes me wonder if maybe we should check through TITLES when they come after a comma (with more than 1 part before the comma) like this, but there's a lot in there. There's a few that could be names, so it could make some cases of "Lastname, Title Firstname" parse incorrectly.

I'm thinking for now to just put "Dr" in with the suffixes too. Let me know if you have other thoughts.

**Comment by Darayavaush** [comment]
Actually, I listed Dr. as an example - I have lots of very rare suffixes (I suspect some of them to be made up) to work with, which is unreasonable to recognize via a whitelist.

What I suggest you do instead is check whether the part before the (last) comma contains more than one word. If it does, then parse it as a name on its own and then mark the part after comma as a suffix.
