### ISSUE TITLE
Wrong parsing of Portuguese prefix "dos" and Hebrew "ben"

### ISSUE THREAD

**Issue by sashaleschuk2** [derek73/python-nameparser#71]
parsing of "Rafael Sousa dos Anjos" returns "Anjos" as the surname when the correct case is "dos Anjos".
parsing of "Oren ben Horin" returns "Horin" as the surname when the correct case is "ben Horin".

**Comment by derek73** [comment]
the problem with "dos" can be fixed by adding it to the prefixes constant. The problem with "ben" cannot be fixed easily because "ben" is much more common as a first name. 

We could write special code to treat "ben" as a prefix only when it is not capitalized but the following piece is capitalized, but that would only fix it if "ben Horin" was properly capitalized.
