### ISSUE TITLE
Tell parser 'this is not a name' or 'this is never a name'

### ISSUE THREAD

**Issue by MalikRumi** [derek73/python-nameparser#80]
`>>> names.human_names
[<HumanName : [
    title: '' 
    first: 'III' 
    middle: 'Briefs of amici curiae urging reversal were filed for the State of Minnesota et al. by Hubert H.' 
    last: 'Humphrey' 
    suffix: ''
    nickname: ''
]>, <HumanName : [
    title: 'Attorney' 
    first: '' 
    middle: '' 
    last: 'General of Minnesota' 
    suffix: ''
    nickname: ''`

I don't see a way to tell the parser that 'III' is *never* going to be a first name, and so should never be parsed as such. I added 'attorney general', 'attorney general of minnesota' and 'Attorney General of Minnesota' as titles, hoping it would automatically pick up on the better choices when I ran it again, but it did not. In the original text, his full name is given, so the parser seems to have assumed it was [last name, first name] instead of [last name, suffix]. And his title at the time was Attorney General, but as you can see, the parser instead made that another human name. 

As for the suffix 'Jr.', that is being presented as the first name or title of the next human name, rather than the suffix of the prior human name. I assume this is because of how it interprets commas. 

If it knew absolutely - or at least in my project, that some suffixes are always only suffixes, and never titles or first names, that would help me a lot. But your code does not seem set up to handle that, and I don't know it well enough to fix it and submit a pull request. 

When it is just "Joe Smith" or "Joe E. Smith", it works perfectly. 

What can be done about these two situations? Any guidance you can give here would be appreciated, and maybe I'll be able to contribute based on what I learn. Thanks.

**Comment by derek73** [comment]
In order to parse "Attorney General of Minnesota" as a title, you would need to add "Minnesota" to the titles set.

```python
>>> from nameparser.config import CONSTANTS
>>> CONSTANTS.titles.add("minnesota")
>>> from nameparser import HumanName
>>> HumanName("Attorney General of Minnesota Lori Swanson")
<HumanName : [
	title: 'Attorney General of Minnesota' 
	first: 'Lori' 
	middle: '' 
	last: 'Swanson' 
	suffix: ''
	nickname: ''
]>
```
Notice that it does not work when the base name parts are missing:

```python
>>> HumanName("Attorney General of Minnesota")
<HumanName : [
	title: 'Attorney' 
	first: '' 
	middle: '' 
	last: 'General of Minnesota' 
	suffix: ''
	nickname: ''
]>
```

This is because the parser assumes that the string you pass it is a name. The name may optionally include pre-nominal or post-nominal name parts like titles and suffixes, but it does not attempt to aid in identifying wether or not a string _is_ a name. The initial use case was for accepting human input, i.e. asking people for their name.

That said, seems like you could potentially use the existing predefined titles to test for strings that are comprised entirely of things that look like titles.

```python
>>> for x in hn:
>>>     print(hn.is_title(x))
True
True
```
That basically just checks to see if the name parts are in the set of titles.

This parser does not do anything probabilistic. It's all deterministic based initially on position in the string and assumptions about where commas can occur in names. 

The example I like to use is "Dean", which is pretty common as both a first name and a title. The parser is only capable of being configured to treat it as one or the other. We could add a set of potentially questionable words like "Dean" and simply set a flag or something when one of these words is found in string. What would you do with that? The truth may be that if you need a deterministic answer to wether or not "Dean" is a first name or title in a specific instance, a human being is probably required, and even they may have to guess.

It looks like you were looking to parse things that look like names and titles from longer bits of text. I would not expect that to work well with this parser. You might find some of the parse helper methods useful like the `is_title()` method above, but they are fairly simple.

https://github.com/derek73/python-nameparser/blob/b9b29cbbbfc138d4958b63e00a047610f30ff6de/nameparser/parser.py#L301-L336

It would be interesting to work on a more machine learning approach that could better understand what "III" is and how that means it can never be a first name. There are interesting observations about names and titles that I've learned working on this project. Some are captured in the tests for this projects along with examples where it currently fails. The challenge might become how to keep it small (or if that is a concern or not). Any noun could potentially be part of a title, and frequently things that aren't recognized as any known word tend to be names. Maybe those things are better implemented as add-ons to existing NLP libraries. But all of that is a bit beyond my current areas of experience and expertise.

I'm going to close this for now because I think what you were trying to do is a bit beyond what this parser project intends to solve for. Feel free to ask questions or let me know if you think there's ways this parser could still be helpful in your situation.
